#' GOSH plot dataset
#'
#' @format Dataset of class \code{gosh.rma}.
#'
#' @source Data generated by fitting a random-effects meta-analysis with \code{rma.uni}
#' using \code{dmetar}s in-built \code{ThirdWave} dataset, which was then provided as input to the
#' \code{gosh} function in \code{metafor}.
#'
#' @usage data("m.gosh")
#'
#' @author Mathias Harrer, David Daniel Ebert
#'
"m.gosh"
